import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import Nav from "@/components/Navigation";

import FinanceContexProvider from "@/lib/store/finance-contex";
import AuthContextProvider from "@/lib/store/auth-contex";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContextProvider>
          <FinanceContexProvider>
            <ToastContainer />
            <Nav />
            {children}
          </FinanceContexProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
