import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Nav from "@/components/Navigation";

import FinanceContexProvider from "@/lib/store/finance-contex";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FinanceContexProvider>
          <Nav />
          {children}
        </FinanceContexProvider>
      </body>
    </html>
  );
}
